baseURL = 'https://jacana.io'
title = 'Jacana.io' # "Jacana Security Research" is a mouthful
theme = 'PaperMod' # https://github.com/adityatelange/hugo-PaperMod
paginate = 5
copyright = '© 2022 Jacana Security Research LLC' # https://creativelawcenter.com/who-owns-copyright/
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true # disabled by default due to security reasons: https://gohugo.io/templates/shortcode-templates/#inline-shortcodes

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true


# Allows info from Git to be used as variables in content: https://gohugo.io/variables/git/#gitinfo-prerequisites
enableGitInfo = true

# Automatically add content sections to main menu
# https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers
# sectionPagesMenu = "main"

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  title = "Jacana.io"
  description = "Landing page for Jacana Security Research"
  keywords = ["blog", "portfolio", "security"]
  author = "Patrick Lloyd"

  images = [] #["/images/jacana-bird-logo-darkbg.svg"]
  DateFormat = "02 January 2006"
  defaultTheme = "dark" # dark, light
  disableThemeToggle = false

  # TODO: Add footer partial with gitinfo
  gitCommitURL = "https://gitlab.com/jacana-security-research/jacana.io/-/commit" 
  
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowWordCount = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  hidemeta = false
  hideSummary = false
  showtoc = true 
  tocopen = false

# TODO: Comments
# https://github.com/adityatelange/hugo-PaperMod/wiki/Features#comments
# https://cactus.chat/docs/integrations/hugo/
  comments = false

  [params.assets]
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon = "/images/favicon.ico"
    favicon16x16 = "/images/favicon16x16.ico"
    favicon32x32 = "/images/favicon32x32.ico"
    #apple_touch_icon = "<link / abs url>"
    #safari_pinned_tab = "<link / abs url>"

  [params.cover]
    linkFullImages = true
    responsiveImages = true

  [params.profileMode]
    enabled = true
    title = "Jacana.io" # optional default will be site title
    subtitle = "We eat bugs for breakfast"
    imageUrl = "/images/jacana-bird-logo-darkbg.svg" # optional
    imageTitle = "Jacana logo" # optional
    imageWidth = 180 # custom size
    imageHeight = 180 # custom size
  
[[params.profileMode.buttons]]
  name= "Archive"
  url= "/archive"
  
[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/"

[[params.socialIcons]]
#icon = "fab fa-gitlab"
name = "GitLab"
url = "https://gitlab.com/jacana-security-research"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/jacana-security-research"

[[params.socialIcons]]
name = "Mastodon"
url = "https://github.com/jacana-security-research"

[[params.socialIcons]]
name = "Contact Us"
url = "/contact/"

[outputs]
home = ["HTML", "RSS", "JSON"]

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.main]]
    identifier = "work"
    name = "Work"
    url = "/work/"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40

  [[menu.main]]
    identifier = "log"
    name = "Log"
    url = "/log/"
    weight = 50

  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 60

  [[menu.main]]
      identifier = "archive"
    name = "Archive"
    url = "/archive/"
    weight = 70



[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# For hugo >= 0.60.0, enable inline HTML
# For the record, this line freaks me out. Why am I allowing unsafe rendering?
#[markup.goldmark.renderer]
#  unsafe = true

[privacy]
  
  [privacy.disqus]
    disable = true
  
  [privacy.googleAnalytics]
    disable = true
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
  
  [privacy.vimeo]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

# see https://gohugo.io/about/security-model/
# [security]
  # enableInlineShortcodes = false
  # [security.exec]
  #   allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  #   osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  # [security.funcs]
  #   getenv = ['^HUGO_']
  # [security.http]
  #   methods = ['(?i)GET|POST']
  #   urls = ['.*']

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses = true

[markup]
  
  [markup.highlight]
    noClasses = false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
