baseURL = 'https://jacana.io'
languageCode = 'en-us'
title = 'Jacana Security Research'
theme = 'jsr-risotto'
author = 'Jacana Security Research'
copyright = '© 2022 Jacana Security Research LLC'
paginate = 3
DefaultContentLanguage = "en-us"
enableInlineShortcodes = true
enableGitInfo = true # gets git information to be used in front matter

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
# I am disabling this because I don't want to use Insta
# ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
# https://gohugo.io/templates/menu-templates/#section-menu-for-lazy-bloggers
sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "Jacana"
description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fab fa-gitlab"
title = "GitLab"
url = "https://gitlab.com/jacana-security-research"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jacana-security-research"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Contact Us"
url = "/contact-us/"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
  unsafe = true

[privacy]

  [privacy.disqus]
    disable = true
  
  [privacy.googleAnalytics]
    disable = true
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false
  
  [privacy.vimeo]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = true
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

# see https://gohugo.io/about/security-model/
# [security]
  # enableInlineShortcodes = false
  # [security.exec]
  #   allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  #   osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
  # [security.funcs]
  #   getenv = ['^HUGO_']
  # [security.http]
  #   methods = ['(?i)GET|POST']
  #   urls = ['.*']

[frontmatter]
  lastmod = [':git', 'lastmod', 'date', 'publishDate'] # default per https://gohugo.io/getting-started/configuration/#configure-front-matter
